tasks:
  - name: Build CLI package
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - |
        VERSION_SUFFIX=$(date +%s)
        dotnet pack --configuration Release --output ./out --version-suffix "${VERSION_SUFFIX}" DamnSmallCI.Cli/DamnSmallCI.Cli.csproj
  
  - name: Build server image
    container:
      image: gcr.io/kaniko-project/executor:debug
      entrypoint: ["sleep", "9999"]
    steps:
      - >-
        /kaniko/executor
        --context "."
        --dockerfile "DamnSmallCi.Server/Dockerfile"
        --no-push
        --tar-path "image.tar"
        --use-new-run
        
  - name: Publish CLI package
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - dotnet nuget push ./out/* --skip-duplicate --source "$NUGET_SOURCE" --api-key "$NUGET_APIKEY"

  - name: Publish server image
    container:
      image: gcr.io/go-containerregistry/crane:debug
      entrypoint: ["sleep", "9999"]
    steps:
      - crane auth login -u $IMAGE_REGISTRY_USER -p $IMAGE_REGISTRY_PASSWORD $IMAGE_REGISTRY
      - crane push image.tar wiiplayer2/damnsmallci-server:latest